### ISSUE TITLE
Update Documentation in Conformance to the Documentation Guide

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziML#24]
### Problem

The current documentation in the module provides a good overview of the API and includes documentation for most public APIs. In line with the newly published [Stanford Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md), we should update the documentation in accordance with the guidelines.

### Solution

The documentation should be updated to provide more insightful inline documentation, improve the README file and the DocC landing page in conformance with the [Stanford Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).

- [x] Update inline documentation, including links and other elements noted in the [Code Documentation section](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md#code-documentation).
- [x] Improve the DocC landing page as detailed in the [Landing Page section](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md#landing-page).
- [x] Add a graphic and visual representation of the module user interface (UI) or UML diagram of the architecture or interacting with the module API.
- [x] Improve the READMe as noted in the [README section](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md#readme).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
This issue was resolved by #36.
